import json
import unicodedata

# Normalizing city names to be able to organize them in alphabetical order
def normalize(s): 
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn')

def ordKey(city):
    return normalize(city['nome'])

f = open("mapa-virtual.json")
bd = json.load(f)
f.close()
cities = bd["cidades"]

cities.sort(key = ordKey)

preHTML = """
<!DOCTYPE html>
<html>
<head>
    <title>Cidades de Portugal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="w3.css">
    <meta charset="utf-8"/>
</head>
<body>
    <div class="w3-card-4">
        <header class="w3-container w3-red">
            <h3>Cidades de Portugal</h3>
        </header>
        <div class="w3-container">
            <ul class="w3-ul w3-card-4" style="width:100%">
"""

posHTML = """
            </ul>
        </div>
        <footer class="w3-container w3-red">
            <h5>Generated by EngWeb2024::A100902</h5>
        </footer>
    </div>
</body>
</html>
"""

content = ""

for c in cities: # r[0] -> número ; r[1] -> nome
    content += f"""
                <li>
                    <a href="http://localhost:7777/{c['id']}.html">
                    {c['nome']}</a>
                </li>
                """

pagHTML = preHTML + content + posHTML

f = open('cidadesSite/index.html', 'w+', encoding='utf-8')
f.write(pagHTML)
print("Index.html created!")
f.close